### ISSUE TITLE
Center position

### ISSUE THREAD

**Issue by tommedema** [alexkuz/react-dock#15]
I would like to have a position `center`. What do you think about this?

**Comment by alexkuz** [comment]
Hm, how would you use that?

**Comment by tommedema** [comment]
It'd simply behave as any component that lies on top of the parent, but with the parent's outer spaces being visible, while the dock occupies the inner space.

I personally use your dock in a chrome extension that allows you to do all sorts of things with the injected page. In my case it would make more sense if the dock was in the vertical and horizontal middle (the center) of the view, rather than it being fixed to one of the edges.

**Comment by alexkuz** [comment]
Well, it seems like you need some kind of popup control, not the actual `react-dock`, isn't it? Centered dock would have completely different behaviour, compared to other states (what about resizing, for example? or show/hide animation?). Is there really something `dock`-specific that you need in your control?

**Comment by tommedema** [comment]
I actually like everything of react-dock; though I guess I could switch to https://github.com/reactjs/react-modal.

Feel free to close if you don't like the idea.

**Comment by alexkuz** [comment]
> I actually like everything of react-dock

Glad to hear it :) It just feels this behavior is out of the scope of this module.
