### ISSUE TITLE
Non Adjustable Dock (fix-width)

### ISSUE THREAD

**Issue by andrefox333** [alexkuz/react-dock#23]
Awesome plugin first of all. Curious on how do I set a fix width on the Dock? I don't want users to be able to able to drag the edges and resize the content of the dock at their will.

Thank you!

**Comment by andrefox333** [comment]
Ah I found the combined settings below worked for what I am looking for. 
```js 
<Dock fluid={false} size={300}></Div>
//size in px
```

**Comment by lucasdu4rte** [comment]
I needed to leave the Dock adaptive to the mobile, using `@media queries` to set the **size** to `'100%'`, but the size only accepts integers, do you know some way to use the **size** for it?
