### ISSUE TITLE
Animation seems to get disabled after controlled size change

### ISSUE THREAD

**Issue by gaearon** [alexkuz/react-dock#4]
Say you have `onSizeChange` handler that updates `size` prop.
1. Drag the resizer
2. The `size` gets updated

Now change the `position` prop.

Expected: position change is animated.
Actual: position change is abrupt. If you then set `visible` to `false` and `true` again, the animation starts to work, but only until next resize.

**Comment by alexkuz** [comment]
should be fixed now

https://github.com/alexkuz/react-dock/commit/170fb0cff6ce5c5369875ca0440a0549c2dae31c
