### ISSUE TITLE
react-vendor-prefixes doesn't support IE8

### ISSUE THREAD

**Issue by SimenB** [alexkuz/react-dock#5]
Is it absolutely necessary? There aren't that many styles that needs the prefix, is it?
ziad-saab/react-vendor-prefixes#2

**Comment by alexkuz** [comment]
OK, I give up on finding proper prefixer :) Just made my own. Please check if it works in IE8.

**Comment by SimenB** [comment]
Yup, that works. Thanks!

A thought is to just manually prefix the ones you need now (during build with `autoprefixr` (https://github.com/uxtemple/autoprefix)? or just hard code them), and have the consumer prefix their own stuff

**Comment by alexkuz** [comment]
It's not that easy to do it in build time, because there are some dynamically created styles, which I don't want to hardcode, actually (not much of it, but still). Anyway, this prefixer seems to work.
