### ISSUE TITLE
Dock is 'global' and does not play well with other docks

### ISSUE THREAD

**Issue by borisyankov** [alexkuz/react-dock#9]
Put a dock on the left, put one on the bottom. They overlap.
If the panel is contained within its parent and is not globally positioned, this will work.
Do you think this scenario should be supported?

**Comment by alexkuz** [comment]
I'm not sure it will work nice, actually.

Also it's not supposed to be on screen permanently, I think, so it's probably better to show one dock at a time, not both of them simultaneously.

(and I'm definitely don't want to build some complicated non-overlapping system like http://www.dockspawn.com/)

**Comment by borisyankov** [comment]
My use case is: three panels, left, right, bottom. Always on screen, but resizeable.
That is why it doesn't work for me;)
Willing to help with PRs if that is a direction you move to.
Or I'll just create a new component that is more in line with what I need. ;)

**Comment by alexkuz** [comment]
Yeah, I suppose you just need a resizable component, not a "dockable" one, so it's a different case. I wouldn't mind a PR though, if you think it could be applied here, but I would start with a new component.
